type Student {
    id: ID!
    name: String!
    age: Int!
    email: String!
    cgpa: Float
}

input StudentInput {
    name: String!
    age: Int!
    email: String!
    cgpa: Float
}

type StudentPage {
    content: [Student!]!
    totalElements: Int!
    totalPages: Int!
    pageNumber: Int!
    pageSize: Int!
    first: Boolean!
    last: Boolean!
}

type Query {
    student(id: ID!): Student
    students(page: Int!, size: Int!): StudentPage!
}

type Mutation {
    createStudent(student: StudentInput!): Student
    updateStudent(id:ID!,student:StudentInput!):Student
    deleteStudent(id:ID!):Boolean!
}